spring:
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
    application:
        name: projecthub
    datasource:
        url: jdbc:mysql://localhost:3306/cloud_storage_db
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
          ddl-auto: create

        properties:
          hibernate:
              dialect: org.hibernate.dialect.MySQL8Dialect
              show_sql: true
              format_sql: true

file:
    storage:
        uploadDir: ./uploads